[debug] [2018-08-22T13:40:04.218Z] ----------------------------------------------------------------------
[debug] [2018-08-22T13:40:04.221Z] Command:       C:\Apps\Nodejs\nodejs\node.exe C:\Apps\Nodejs\npm\node_modules\firebase-tools\bin\firebase login
[debug] [2018-08-22T13:40:04.221Z] CLI Version:   3.19.3
[debug] [2018-08-22T13:40:04.221Z] Platform:      win32
[debug] [2018-08-22T13:40:04.221Z] Node Version:  v8.11.3
[debug] [2018-08-22T13:40:04.222Z] Time:          Wed Aug 22 2018 15:40:04 GMT+0200 (Paris, Madrid (heure d’été))
[debug] [2018-08-22T13:40:04.222Z] ----------------------------------------------------------------------
[debug] 
[info] 
[info] Visit this URL on any device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=299423635&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2018-08-22T13:40:21.027Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  
 { code: '4/QwD6FDNJ04IGrY03AYllbv9Kwe3H-jGZBouIRXAL4e2aIImIK6iLMYrdIDD1f8VhDRsJ4B1yZzmVY_97b5LJyos',
  client_id: '563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com',
  client_secret: 'j9iVZfS8kkCEFUPaAeJV0sAi',
  redirect_uri: 'http://localhost:9005',
  grant_type: 'authorization_code' } 
 Wed Aug 22 2018 15:40:21 GMT+0200 (Paris, Madrid (heure d’été))
[debug] [2018-08-22T13:40:42.037Z] Token Fetch Error: Error
    at new FirebaseError (C:\Apps\Nodejs\npm\node_modules\firebase-tools\lib\error.js:11:16)
    at Request._callback (C:\Apps\Nodejs\npm\node_modules\firebase-tools\lib\api.js:35:11)
    at self.callback (C:\Apps\Nodejs\npm\node_modules\firebase-tools\node_modules\request\request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Apps\Nodejs\npm\node_modules\firebase-tools\node_modules\request\request.js:877:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
[debug] [2018-08-22T13:41:05.509Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  
 { code: '4/QwAnrdty7VGj1hZvViT0FA5XdQUn3bRryKE643ZMSrRwqrTBK6c4MuuqiDNSI1Q3kcjhDZJSB8QTOzfGrbiAtt4',
  client_id: '563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com',
  client_secret: 'j9iVZfS8kkCEFUPaAeJV0sAi',
  redirect_uri: 'http://localhost:9005',
  grant_type: 'authorization_code' } 
 Wed Aug 22 2018 15:41:05 GMT+0200 (Paris, Madrid (heure d’été))
[debug] [2018-08-22T13:41:26.514Z] Token Fetch Error: Error
    at new FirebaseError (C:\Apps\Nodejs\npm\node_modules\firebase-tools\lib\error.js:11:16)
    at Request._callback (C:\Apps\Nodejs\npm\node_modules\firebase-tools\lib\api.js:35:11)
    at self.callback (C:\Apps\Nodejs\npm\node_modules\firebase-tools\node_modules\request\request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Apps\Nodejs\npm\node_modules\firebase-tools\node_modules\request\request.js:877:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
[debug] [2018-08-22T13:42:04.468Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  
 { code: '4/QwAnrdty7VGj1hZvViT0FA5XdQUn3bRryKE643ZMSrRwqrTBK6c4MuuqiDNSI1Q3kcjhDZJSB8QTOzfGrbiAtt4',
  client_id: '563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com',
  client_secret: 'j9iVZfS8kkCEFUPaAeJV0sAi',
  redirect_uri: 'http://localhost:9005',
  grant_type: 'authorization_code' } 
 Wed Aug 22 2018 15:42:04 GMT+0200 (Paris, Madrid (heure d’été))
[debug] [2018-08-22T13:42:25.468Z] Token Fetch Error: Error
    at new FirebaseError (C:\Apps\Nodejs\npm\node_modules\firebase-tools\lib\error.js:11:16)
    at Request._callback (C:\Apps\Nodejs\npm\node_modules\firebase-tools\lib\api.js:35:11)
    at self.callback (C:\Apps\Nodejs\npm\node_modules\firebase-tools\node_modules\request\request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Apps\Nodejs\npm\node_modules\firebase-tools\node_modules\request\request.js:877:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
[debug] [2018-08-22T13:43:37.660Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  
 { code: '4/QwDFymT8hjSUI7zziTK455S9WjMhlkm0x5myJb8sZ4tXfFrTTl0yQ6cQmgrzYPTDbiHe4PSprP3mmIe9qLsQTys',
  client_id: '563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com',
  client_secret: 'j9iVZfS8kkCEFUPaAeJV0sAi',
  redirect_uri: 'http://localhost:9005',
  grant_type: 'authorization_code' } 
 Wed Aug 22 2018 15:43:37 GMT+0200 (Paris, Madrid (heure d’été))
[debug] [2018-08-22T13:43:58.666Z] Token Fetch Error: Error
    at new FirebaseError (C:\Apps\Nodejs\npm\node_modules\firebase-tools\lib\error.js:11:16)
    at Request._callback (C:\Apps\Nodejs\npm\node_modules\firebase-tools\lib\api.js:35:11)
    at self.callback (C:\Apps\Nodejs\npm\node_modules\firebase-tools\node_modules\request\request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Apps\Nodejs\npm\node_modules\firebase-tools\node_modules\request\request.js:877:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
